import { createContext, useState } from "react";
import { FormState } from "./FormState";
    import { Item } from "@db/items/types";
    import { VendorType } from "@db/vendors";
    import Brand from "@features/brands/type";
    import React from "react";


export const FormStateContext = createContext<FormState>({
    
    selectedRecipeBatchId: 0,
    setSelectedRecipeBatchId: () => {},
    selectedRecipeBatchName: '',
    setSelectedRecipeBatchName: () => {},
    nuteConcentration: '',
    setNuteConcentration: () => {},
    isNew: false,
    setIsNew: () => {},
    selectedItem: null,
    setSelectedItem: () => {},
    id: null,
    setId: () => {},
    name: "", 
    setName: (name: string) => {},
    category: "", 
    setCategory: () => {},
    subcategory: "", 
    setSubcategory: () => {},
    item: null,
    setItem: () => {},
    items: [],
    setItems: () => {},
    itemId: 0,
    setItemId: () => {},
    formVisible: false,
    setFormVisible: () => {},
    pickedImageUri: "",
    setPickedImageUri: () => {},
    brand: null, 
    setBrand: () => {},
    newBrand: false,
    setNewBrand: () => {},
    purchaseQuantity: "",
    setPurchaseQuantity: () => {},
    purchaseUnit: "",
    setPurchaseUnit: () => {},
    inventoryQuantity: "",
    setInventoryQuantity: () => {},
    inventoryUnit: "",
    setInventoryUnit: () => {},
    cost: "", 
    setCost: () => {},
    receiptPath: "",
    setReceiptPath: () => {},
    notes: "", 
    setNotes: () => {},
    vendorId: 0,
    setVendorId: () => {},
    brandId: 0,
    setBrandId: () => {},
    vendors: null,
    setVendors: () => {},
    brands: null, 
    setBrands: () => {},
    newVendor: false,
    setNewVendor: () => {},
    vendorPhone: "",
    setVendorPhone: () => {},
    vendorEmail: "",
    setVendorEmail: () => {},
    vendorWebsite: "",
    setVendorWebsite: () => {},
    image: null, 
    setImage: () => {},
    images: [], 
    setImages: () => {},
    contentType: "",
    setContentType: () => {},
    receiptMemo: "",
    setReceiptMemo: () => {},
    purchaseDatetime: new Date(),
    setPurchaseDatetime: () => {}
    
});
