import { Item } from "@db/items/types";
import { VendorType } from "@db/vendors";
import Brand from "@features/brands/type";
import React from "react";

export interface FormState {
        type: string,
        setType:  React.Dispatch<React.SetStateAction<string>>,
        selectedRecipeBatchId: number, 
        setSelectedRecipeBatchId: React.Dispatch<React.SetStateAction<number>>,
        selectedRecipeBatchName: string, 
        setSelectedRecipeBatchName: React.Dispatch<React.SetStateAction<string>>,
        nuteConcentration: string,
        setNuteConcentration: React.Dispatch<React.SetStateAction<string>>,
        isNew: boolean,
        setIsNew: React.Dispatch<React.SetStateAction<boolean>>,
        id: number, 
        setId: React.Dispatch<React.SetStateAction<number>>,
        selectedItem: Item,
        setSelectedItem: React.Dispatch<React.SetStateAction<Item>>,
        name: string, 
        setName: React.Dispatch<React.SetStateAction<string>>,
        category: string, 
        setCategory: React.Dispatch<React.SetStateAction<string>>,
        subcategory: string, 
        setSubcategory: React.Dispatch<React.SetStateAction<string>>,
        item: Item,
        setItem: React.Dispatch<React.SetStateAction<Item>>,
        items: Item[],
        setItems: React.Dispatch<React.SetStateAction<Item[]>>,
        itemId: number,
        setItemId: React.Dispatch<React.SetStateAction<number>>,
        formVisible: boolean,
        setFormVisible: React.Dispatch<React.SetStateAction<boolean>>,
        pickedImageUri: string,
        setPickedImageUri: React.Dispatch<React.SetStateAction<string>>,
        brand: any, 
        setBrand: React.Dispatch<React.SetStateAction<any>>,
        newBrand: boolean,
        setNewBrand: React.Dispatch<React.SetStateAction<boolean>>,
        purchaseQuantity: string,
        setPurchaseQuantity: React.Dispatch<React.SetStateAction<string>>,
        purchaseUnit: string,
        setPurchaseUnit: React.Dispatch<React.SetStateAction<string>>,
        inventoryQuantity: string,
        setInventoryQuantity: React.Dispatch<React.SetStateAction<string>>,
        inventoryUnit: string,
        setInventoryUnit: React.Dispatch<React.SetStateAction<string>>,
        cost: string, 
        setCost: React.Dispatch<React.SetStateAction<string>>,
        receiptPath: string,
        setReceiptPath: React.Dispatch<React.SetStateAction<string>>,
        notes: string, 
        setNotes: React.Dispatch<React.SetStateAction<string>>,
        vendorId: number,
        setVendorId: React.Dispatch<React.SetStateAction<number>>,
        brandId: number,
        setBrandId: React.Dispatch<React.SetStateAction<number>>,
        vendors: VendorType[],
        setVendors: React.Dispatch<React.SetStateAction<VendorType[]>>,
        vendor: VendorType,
        setVendor: React.Dispatch<React.SetStateAction<VendorType>>,
        brands: Brand[], 
        setBrands: React.Dispatch<React.SetStateAction<Brand[]>>,
        newVendor: boolean,
        setNewVendor: React.Dispatch<React.SetStateAction<boolean>>,
        image: any, 
        setImage: React.Dispatch<React.SetStateAction<any>>,
        images: any[], 
        setImages: React.Dispatch<React.SetStateAction<any[]>>,
        contentType: string,
        setContentType: React.Dispatch<React.SetStateAction<string>>,
        receiptMemo: string,
        setReceiptMemo: React.Dispatch<React.SetStateAction<string>>,
        purchaseDatetime: Date,
        setPurchaseDatetime: React.Dispatch<React.SetStateAction<Date>>

}

export interface NewBrandFormState {
        brandName: string,
        setBrandName: React.Dispatch<React.SetStateAction<string>>,
        brandWebsite: string,
        setBrandWebsite: React.Dispatch<React.SetStateAction<string>>
}
        
export interface NewVendorFormState {
        phone: string,
        setPhone: React.Dispatch<React.SetStateAction<string>>,
        email: string,
        setEmail: React.Dispatch<React.SetStateAction<string>>,
        website: string,
        setWebsite: React.Dispatch<React.SetStateAction<string>>,
        name: string,
        setName: React.Dispatch<React.SetStateAction<string>>,
        address: string,
        setAddress: React.Dispatch<React.SetStateAction<string>>,
        contactName: string,
        setContactName: React.Dispatch<React.SetStateAction<string>>
}
