import { Item } from "@db/items/types";
import { VendorType } from "@db/vendors";
import Brand from "@features/brands/type";
import React from "react";

export interface FormState {
        selectedRecipeBatchId: number, 
        setSelectedRecipeBatchId: React.Dispatch<React.SetStateAction<number>>,
        selectedRecipeBatchName: string, 
        setSelectedRecipeBatchName: React.Dispatch<React.SetStateAction<string>>
        nuteConcentration: string,
        setNuteConcentration: React.Dispatch<React.SetStateAction<string>>,
        isNew: boolean,
        setIsNew: React.Dispatch<React.SetStateAction<boolean>>,
        id: number, 
        setId: React.Dispatch<React.SetStateAction<number>>,
        selectedItem: Item,
        setSelectedItem: React.Dispatch<React.SetStateAction<Item>>,
        name: string, 
        setName: React.Dispatch<React.SetStateAction<string>>,
        category: string, 
        setCategory: React.Dispatch<React.SetStateAction<string>>,
        subcategory: string, 
        setSubcategory: React.Dispatch<React.SetStateAction<string>>,
        items: Item[],
        setItems: React.Dispatch<React.SetStateAction<Item[]>>,
        formVisible: boolean,
        setFormVisible: React.Dispatch<React.SetStateAction<boolean>>,
        pickedImageUri: string,
        setPickedImageUri: React.Dispatch<React.SetStateAction<string>>,
        brand: any, 
        setBrand: React.Dispatch<React.SetStateAction<any>>,
        newBrand: boolean,
        setNewBrand: React.Dispatch<React.SetStateAction<boolean>>,
        purchaseQuantity: string,
        setPurchaseQuantity: React.Dispatch<React.SetStateAction<string>>,
        purchaseUnit: string,
        setPurchaseUnit: React.Dispatch<React.SetStateAction<string>>,
        inventoryQuantity: string,
        setInventoryQuantity: React.Dispatch<React.SetStateAction<string>>,
        inventoryUnit: string,
        setInventoryUnit: React.Dispatch<React.SetStateAction<string>>,
        cost: string, 
        setCost: React.Dispatch<React.SetStateAction<string>>,
        receiptPath: string,
        setReceiptPath: React.Dispatch<React.SetStateAction<string>>,
        notes: string, 
        setNotes: React.Dispatch<React.SetStateAction<string>>,
        vendorId: number,
        setVendorId: React.Dispatch<React.SetStateAction<number>>,
        brandId: number,
        setBrandId: React.Dispatch<React.SetStateAction<number>>,
        vendors: VendorType[],
        setVendors: React.Dispatch<React.SetStateAction<VendorType[]>>,
        brands: Brand[], 
        setBrands: React.Dispatch<React.SetStateAction<Brand[]>>,
        newVendor: boolean,
        setNewVendor: React.Dispatch<React.SetStateAction<boolean>>,
        vendorPhone: string,
        setVendorPhone: React.Dispatch<React.SetStateAction<string>>,
        vendorEmail: string,
        setVendorEmail: React.Dispatch<React.SetStateAction<string>>,
        vendorWebsite: string,
        setVendorWebsite: React.Dispatch<React.SetStateAction<string>>,
        image: any, 
        setImage: React.Dispatch<React.SetStateAction<any>>,
        contentType: string,
        setContentType: React.Dispatch<React.SetStateAction<string>>,
        receiptMemo: string,
        setReceiptMemo: React.Dispatch<React.SetStateAction<string>>,
        purchaseDatetime: Date,
        setPurchaseDatetime: React.Dispatch<React.SetStateAction<Date>>

}